// @generated by LogicGraph
// logicgraph-ui-contract: UI-INVOICE-001
import { expect, test, type Locator, type Page } from "@playwright/test";

const route = "/invoices/fixture-paid";

test("UI-INVOICE-001: Download invoice button", async ({ page }) => {
  const baseUrl = process.env.LOGICGRAPH_BASE_URL;
  if (!baseUrl) {
    throw new Error("LOGICGRAPH_BASE_URL is required. Run logicgraph verify run so .logicgraph/config.yaml verify.baseUrl is used.");
  }

  await page.goto(new URL(route, baseUrl).toString());

  const subject = page.getByRole("button" as never, { name: "Download invoice" });
  await expect(subject).toBeVisible();

  await subject.click();

  await expectTextVisible(page, "Download invoice");
});

async function findByTarget(page: Page, target: string): Promise<Locator> {
  const value = cssString(target);
  const byTestId = page.locator(`[data-testid="${value}"]`);
  try {
    await expect(byTestId).toBeAttached();
    return byTestId;
  } catch (error) {
    if (error instanceof Error && error.message.includes("strict mode violation")) {
      throw error;
    }
    return page.locator(`[id="${value}"]`);
  }
}

function cssString(value: string): string {
  return value.replace(/[\0-\x1f\x7f"\\]/g, (char) => {
    if (char === "\"" || char === "\\") {
      return `\\${char}`;
    }
    return `\\${char.charCodeAt(0).toString(16)} `;
  });
}

async function expectTextVisible(root: Page | Locator, text: string): Promise<void> {
  const matches = root.getByText(text);
  await expect.poll(async () => {
    for (let index = 0; index < await matches.count(); index++) {
      if (await matches.nth(index).isVisible()) {
        return true;
      }
    }
    return false;
  }).toBe(true);
}
