import { chmod, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, sep } from "node:path";
import { describe, expect, it } from "vitest";
import {
  formatRunResult,
  formatScaffoldResult,
  playwrightCommand,
  parsePlaywrightReport,
  runUiVerification,
  scaffoldUiVerification,
} from "../src/commands/verify.js";

describe("verify commands", () => {
  it("scaffolds specs and records tests evidence idempotently", async () => {
    const cwd = await project(contractYaml());

    const first = await scaffoldUiVerification({ cwd });

    expect(first.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "generated", updatedContract: true }]);
    expect(formatScaffoldResult(first)).toContain("✓ UI-INVOICE-001  tests/logicgraph/UI-INVOICE-001.spec.ts");
    const specPath = join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts");
    const spec = await readFile(specPath, "utf8");
    expect(spec).toContain("logicgraph-ui-contract: UI-INVOICE-001");
    expect(await readFile(join(cwd, ".logicgraph", "ui-contracts", "UI-INVOICE-001.yaml"), "utf8")).toContain("tests/logicgraph/UI-INVOICE-001.spec.ts");
    await writeFile(specPath, spec.replace(/\n/g, "\r\n"), "utf8");

    const second = await scaffoldUiVerification({ cwd });

    expect(second.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "unchanged", updatedContract: false }]);
  });

  it("refuses to overwrite unowned spec files", async () => {
    const cwd = await project(contractYaml());
    await mkdir(join(cwd, "tests", "logicgraph"), { recursive: true });
    const spec = join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts");
    const handAuthored = "// hand-authored test\nconst fixture = `// @generated by LogicGraph\n// logicgraph-ui-contract: UI-INVOICE-001`;\n";
    await writeFile(spec, handAuthored, "utf8");

    const result = await scaffoldUiVerification({ cwd });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "refusing to overwrite unowned spec tests/logicgraph/UI-INVOICE-001.spec.ts", updatedContract: false }]);
    expect(await readFile(spec, "utf8")).toBe(handAuthored);
    expect(await readFile(join(cwd, ".logicgraph", "ui-contracts", "UI-INVOICE-001.yaml"), "utf8")).not.toContain("tests:");
  });

  it("requires an exact generated ownership header", async () => {
    const cwd = await project(contractYaml());
    await mkdir(join(cwd, "tests", "logicgraph"), { recursive: true });
    const spec = join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts");
    const otherGenerated = "// @generated by LogicGraph\n// logicgraph-ui-contract: UI-INVOICE-001-OLD\n";
    await writeFile(spec, otherGenerated, "utf8");

    const result = await scaffoldUiVerification({ cwd });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "refusing to overwrite unowned spec tests/logicgraph/UI-INVOICE-001.spec.ts" }]);
    expect(await readFile(spec, "utf8")).toBe(otherGenerated);
  });

  it("reports deprecated scaffold items as skipped", async () => {
    const cwd = await project(contractYaml().replace("status: active", "status: deprecated"));

    const result = await scaffoldUiVerification({ cwd });

    expect(formatScaffoldResult(result)).toContain("⚠ UI-INVOICE-001  skipped: deprecated contract");
  });

  it("does not duplicate normalized generated test evidence", async () => {
    const cwd = await project(`${contractYaml()}tests:\n  - ./tests/logicgraph/UI-INVOICE-001.spec.ts\n`);

    const result = await scaffoldUiVerification({ cwd });
    const contract = await readFile(join(cwd, ".logicgraph", "ui-contracts", "UI-INVOICE-001.yaml"), "utf8");

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", updatedContract: false }]);
    expect(contract.match(/UI-INVOICE-001\.spec\.ts/g)).toHaveLength(1);
  });

  it("refuses to write through dangling spec symlinks outside the repository", async () => {
    const cwd = await project(contractYaml());
    await mkdir(join(cwd, "tests", "logicgraph"), { recursive: true });
    const outside = await mkdtemp(join(tmpdir(), "logicgraph-outside-spec-"));
    await symlink(join(outside, "UI-INVOICE-001.spec.ts"), join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts"));

    const result = await scaffoldUiVerification({ cwd });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "refusing to write generated spec: tests/logicgraph/UI-INVOICE-001.spec.ts is a symlink; refusing to write generated specs through symlinks" }]);
    await expect(readFile(join(outside, "UI-INVOICE-001.spec.ts"), "utf8")).rejects.toThrow("ENOENT");
  });

  it("refuses to write through chained spec symlinks outside the repository", async () => {
    const cwd = await project(contractYaml());
    await mkdir(join(cwd, "tests", "logicgraph"), { recursive: true });
    const outside = await mkdtemp(join(tmpdir(), "logicgraph-outside-spec-"));
    await symlink(join(outside, "final.spec.ts"), join(cwd, "tests", "logicgraph", "inner.spec.ts"));
    await symlink(join(cwd, "tests", "logicgraph", "inner.spec.ts"), join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts"));

    const result = await scaffoldUiVerification({ cwd });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "refusing to write generated spec: tests/logicgraph/UI-INVOICE-001.spec.ts is a symlink; refusing to write generated specs through symlinks" }]);
    await expect(readFile(join(outside, "final.spec.ts"), "utf8")).rejects.toThrow("ENOENT");
  });

  it("reports non-file generated spec targets", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });
    const specPath = join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts");
    await rm(specPath);
    await mkdir(specPath);

    const scaffold = await scaffoldUiVerification({ cwd });
    const run = await runUiVerification({ cwd, runner: async () => playwrightResult("passed") });

    expect(scaffold.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "refusing to write generated spec: tests/logicgraph/UI-INVOICE-001.spec.ts is not a file" }]);
    expect(run.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "generated spec tests/logicgraph/UI-INVOICE-001.spec.ts is not a file" }]);
  });

  it("reports generated spec target inspection errors", async () => {
    const longId = `UI-${"A".repeat(5000)}`;
    const cwd = await project(contractYaml().replace("id: UI-INVOICE-001", `id: ${longId}`));

    const result = await scaffoldUiVerification({ cwd });

    expect(result.items).toHaveLength(1);
    expect(result.items[0]).toMatchObject({ contractId: longId, status: "failed", updatedContract: false });
    expect(result.items[0].reason).toContain("refusing to write generated spec:");
    expect(result.items[0].reason).toContain("could not be inspected");
  });

  it("keeps scaffold and run stable when cwd is a symlink", async () => {
    const realCwd = await project(contractYaml());
    const symlinkCwd = await mkdtemp(join(tmpdir(), "logicgraph-linked-cwd-parent-"));
    const link = join(symlinkCwd, "app");
    await symlink(realCwd, link, "dir");

    await scaffoldUiVerification({ cwd: link });
    const second = await scaffoldUiVerification({ cwd: link });
    let seenArgs: string[] = [];
    const run = await runUiVerification({ cwd: link, runner: async (args) => {
      seenArgs = args;
      return playwrightResult("passed");
    } });

    expect(second.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "unchanged", updatedContract: false }]);
    expect(run.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "passed" }]);
    expect(seenArgs.at(-1)).toBe(escapedPathFilter(join(realCwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts")));
  });

  it("filters real generated spec paths through symlinked spec directories", async () => {
    const cwd = await project(contractYaml(), "verify:\n  baseUrl: http://localhost:3443\n  specDir: generated\n  pages:\n    InvoiceDetails: /invoices/fixture-paid\n");
    await mkdir(join(cwd, "tests", "logicgraph"), { recursive: true });
    await symlink(join(cwd, "tests", "logicgraph"), join(cwd, "generated"), "dir");
    await scaffoldUiVerification({ cwd });
    let seenArgs: string[] = [];

    const result = await runUiVerification({ cwd, runner: async (args) => {
      seenArgs = args;
      return playwrightResult("passed");
    } });

    expect(result.items).toEqual([{ contractId: "UI-INVOICE-001", status: "passed", specRelativePath: "generated/UI-INVOICE-001.spec.ts" }]);
    expect(seenArgs).toEqual(["test", "--reporter=json", "--", escapedPathFilter(join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts"))]);
  });

  it("passes generated specs after Playwright's option separator", async () => {
    const cwd = await project(contractYaml(), "verify:\n  baseUrl: http://localhost:3443\n  specDir: '--project=[chromium]'\n  pages:\n    InvoiceDetails: /invoices/fixture-paid\n");
    await scaffoldUiVerification({ cwd });
    const specPath = join(cwd, "--project=[chromium]", "UI-INVOICE-001.spec.ts");
    await writeFile(specPath, (await readFile(specPath, "utf8")).replace(/\n/g, "\r\n"), "utf8");
    let seenArgs: string[] = [];

    const result = await runUiVerification({ cwd, runner: async (args, options) => {
      seenArgs = args;
      expect(options.env.LOGICGRAPH_BASE_URL).toBe("http://localhost:3443");
      expect(options.env.PLAYWRIGHT_JSON_OUTPUT_FILE).toMatch(/report\.json$/);
      return playwrightResult("passed");
    } });

    expect(result.items).toEqual([{ contractId: "UI-INVOICE-001", status: "passed", specRelativePath: "--project=[chromium]/UI-INVOICE-001.spec.ts" }]);
    expect(seenArgs).toEqual(["test", "--reporter=json", "--", escapedPathFilter(specPath)]);
    expect(formatRunResult(result)).toContain("✓ UI-INVOICE-001  passed");
  });

  it("reports a missing local Playwright binary without invoking npx", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });

    const result = await runUiVerification({ cwd });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "Playwright JSON report unavailable: Playwright binary not found at node_modules/.bin/playwright. Install Playwright in this project." }]);
  });

  it("runs the local Playwright binary", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });
    const command = playwrightCommand(cwd);
    await mkdir(join(cwd, "node_modules", ".bin"), { recursive: true });
    await writeFile(command, `#!/bin/sh\nprintf '%s' '${playwrightResult("passed").stdout}' > "$PLAYWRIGHT_JSON_OUTPUT_FILE"\n`, "utf8");
    await chmod(command, 0o755);

    const result = await runUiVerification({ cwd });

    expect(result.items).toEqual([{ contractId: "UI-INVOICE-001", status: "passed", specRelativePath: "tests/logicgraph/UI-INVOICE-001.spec.ts" }]);
  });

  it("reads the JSON reporter output from its dedicated file", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });
    const previous = process.env.PLAYWRIGHT_JSON_OUTPUT_FILE;
    process.env.PLAYWRIGHT_JSON_OUTPUT_FILE = join(cwd, "caller-report.json");
    let reportPath = "";

    try {
      const result = await runUiVerification({ cwd, runner: async (_args, options) => {
        expect(options.env.PLAYWRIGHT_JSON_OUTPUT_FILE).not.toBe(process.env.PLAYWRIGHT_JSON_OUTPUT_FILE);
        reportPath = String(options.env.PLAYWRIGHT_JSON_OUTPUT_FILE);
        await writeFile(reportPath, playwrightResult("passed").stdout, "utf8");
        return { stdout: "global setup noise", stderr: "", exitCode: 0 };
      } });

      expect(result.items).toEqual([{ contractId: "UI-INVOICE-001", status: "passed", specRelativePath: "tests/logicgraph/UI-INVOICE-001.spec.ts" }]);
      await expect(readFile(reportPath, "utf8")).rejects.toThrow("ENOENT");
    } finally {
      if (previous === undefined) {
        delete process.env.PLAYWRIGHT_JSON_OUTPUT_FILE;
      } else {
        process.env.PLAYWRIGHT_JSON_OUTPUT_FILE = previous;
      }
    }
  });

  it("fails run when the generated spec is stale", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });
    await writeFile(join(cwd, "tests", "logicgraph", "UI-INVOICE-001.spec.ts"), "// stale", "utf8");
    let called = false;

    const result = await runUiVerification({ cwd, runner: async () => {
      called = true;
      return playwrightResult("passed");
    } });

    expect(called).toBe(false);
    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "generated spec is stale; run logicgraph verify scaffold UI-INVOICE-001" }]);
  });

  it("reports partial when the contract has unknown expected types", async () => {
    const cwd = await project(contractYaml("  - type: profile-saved\n"));
    await scaffoldUiVerification({ cwd });

    const result = await runUiVerification({ cwd, runner: async () => playwrightResult("passed") });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "partial", reason: 'unknown expected type "profile-saved"' }]);
    expect(formatRunResult(result)).toContain('⚠ UI-INVOICE-001  partial: unknown expected type "profile-saved"');
  });

  it("reports failed when Playwright reports a failed spec", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });

    const result = await runUiVerification({ cwd, runner: async () => playwrightResult("failed") });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed" }]);
    expect(formatRunResult(result)).toContain("✗ UI-INVOICE-001  failed");
  });

  it("fails run when Playwright exits nonzero despite passed suite results", async () => {
    const cwd = await project(contractYaml());
    await scaffoldUiVerification({ cwd });

    const result = await runUiVerification({ cwd, runner: async () => ({ ...playwrightResult("passed"), exitCode: 1, stderr: "global teardown failed" }) });

    expect(result.items).toMatchObject([{ contractId: "UI-INVOICE-001", status: "failed", reason: "Playwright exited with code 1: global teardown failed" }]);
  });

  it("fails passed specs when the Playwright report includes runner errors", async () => {
    const cwd = await project(contractYaml());
    await writeFile(join(cwd, ".logicgraph", "ui-contracts", "UI-INVOICE-002.yaml"), contractYaml().replace("UI-INVOICE-001", "UI-INVOICE-002"), "utf8");
    await scaffoldUiVerification({ cwd });

    const result = await runUiVerification({ cwd, runner: async () => ({
      stdout: JSON.stringify({
        suites: [
          { file: "tests/logicgraph/UI-INVOICE-001.spec.ts", specs: [{ tests: [{ results: [{ status: "failed" }] }] }] },
          { file: "tests/logicgraph/UI-INVOICE-002.spec.ts", specs: [{ tests: [{ results: [{ status: "passed" }] }] }] },
        ],
        errors: [{ message: "global teardown failed" }],
      }),
      stderr: "",
      exitCode: 1,
    }) });

    expect(result.items).toEqual([
      { contractId: "UI-INVOICE-001", status: "failed", specRelativePath: "tests/logicgraph/UI-INVOICE-001.spec.ts", reason: "Playwright report errors: global teardown failed" },
      { contractId: "UI-INVOICE-002", status: "failed", specRelativePath: "tests/logicgraph/UI-INVOICE-002.spec.ts", reason: "Playwright report errors: global teardown failed" },
    ]);
  });

  it("requires baseUrl for verify run", async () => {
    const cwd = await project(contractYaml(), "verify:\n  pages:\n    InvoiceDetails: /invoices/fixture-paid\n");
    await scaffoldUiVerification({ cwd });

    await expect(runUiVerification({ cwd, runner: async () => playwrightResult("passed") })).rejects.toThrow("verify.baseUrl is required");
  });

  it("parses nested Playwright JSON suites", () => {
    const report = parsePlaywrightReport(JSON.stringify({ suites: [{ suites: [{ file: "tests/logicgraph/UI-INVOICE-001.spec.ts", specs: [{ tests: [{ results: [{ status: "passed" }] }] }] }] }] }));

    expect(report).toMatchObject({ ok: true });
    if (report.ok) {
      expect(report.statuses.get("UI-INVOICE-001")).toBe("passed");
    }
  });

  it("uses the final Playwright retry outcome", () => {
    const report = parsePlaywrightReport(JSON.stringify({ suites: [{ file: "tests/logicgraph/UI-INVOICE-001.spec.ts", specs: [{ tests: [{ results: [{ status: "failed" }, { status: "passed" }] }] }] }] }));

    expect(report).toMatchObject({ ok: true });
    if (report.ok) {
      expect(report.statuses.get("UI-INVOICE-001")).toBe("passed");
    }
  });

  it("treats skipped-only Playwright results as failed", () => {
    const report = parsePlaywrightReport(JSON.stringify({ suites: [{ file: "tests/logicgraph/UI-INVOICE-001.spec.ts", specs: [{ tests: [{ results: [{ status: "skipped" }] }] }] }] }));

    expect(report).toMatchObject({ ok: true });
    if (report.ok) {
      expect(report.statuses.get("UI-INVOICE-001")).toBe("failed");
    }
  });

  it("uses the local Playwright command name", () => {
    expect(playwrightCommand("repo", "win32")).toBe(join("repo", "node_modules", ".bin", "playwright.cmd"));
    expect(playwrightCommand("repo", "linux")).toBe(join("repo", "node_modules", ".bin", "playwright"));
  });
});

async function project(contract: string, verify = "verify:\n  baseUrl: http://localhost:3443\n  pages:\n    InvoiceDetails: /invoices/fixture-paid\n"): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "logicgraph-verify-cli-"));
  await mkdir(join(cwd, ".logicgraph", "rules"), { recursive: true });
  await mkdir(join(cwd, ".logicgraph", "ui-contracts"), { recursive: true });
  await writeFile(join(cwd, ".logicgraph", "config.yaml"), `version: 1\nrules: rules\nuiContracts: ui-contracts\njourneys: journeys\n${verify}`, "utf8");
  await writeFile(join(cwd, ".logicgraph", "ui-contracts", "UI-INVOICE-001.yaml"), contract, "utf8");
  return cwd;
}

function contractYaml(expected = "  - type: text-visible\n    text: Download\n"): string {
  return `id: UI-INVOICE-001
title: Download invoice button
status: active
page: InvoiceDetails
element:
  id: download_invoice_button
  role: button
  label: Download
trigger:
  event: click
expected:
${expected}`;
}

function playwrightResult(status: "passed" | "failed" | "skipped") {
  return {
    stdout: JSON.stringify({
      suites: [{
        file: "tests/logicgraph/UI-INVOICE-001.spec.ts",
        specs: [{ tests: [{ results: [{ status }] }] }],
      }],
    }),
    stderr: "",
    exitCode: status === "passed" ? 0 : 1,
  };
}

function escapedPathFilter(path: string): string {
  return `^${path.split(sep).map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("[/\\\\]")}$`;
}
